### ISSUE TITLE
Content Fulfillment (Bernardo)

### ISSUE THREAD

**Issue by rayfarias56** [rayfarias56/shpe#116]
## Pages
- [x] Web Dev Committee Page
- [x] All Meeting Times Page
- [x] Home
- [x] Student Advisor

**Comment by rayfarias56** [comment]
http://bootsnipp.com/snippets/featured/no-more-tables-respsonsive-table

Responsive table for developers, ensure to note whether they are active or not. 

Please look at how eboard is set in the eboard (or members) page and here: https://github.com/rayfarias56/shpe/blob/659c89841f20fa8c80ba2faba1426f668ae681d6/config/initializers/constants.rb#L21 in order to get an idea of how to use an embedded ruby for loop to construct the table. If you want you may also want to look into a whether or not constants is a good method for this (we may need to store developers in the db).

**Comment by NoxelSarahue** [comment]
Updated Student Advisory and Meeting Times. Lost the paper with basic layout for meeting times so I made it similar to the contacts page. Also have yet to implement the responsive tables, or note which developers are active or inactive
