### ISSUE TITLE
Embedded Calendar

### ISSUE THREAD

**Issue by rayfarias56** [rayfarias56/shpe#124]
The eboard would like the events page to be an embedded google calendar.

**Comment by rayfarias56** [comment]
Swapped to victoria because this will now be the entire events page #117

**Comment by haugerbr** [comment]
Just an fyi, changing that page might have broken attendance with the card reader. Also why did the eboard want an embedded Google calendar? Using that will pretty much create a bad experience on mobile for viewing events.

**Comment by rayfarias56** [comment]
Why would it break attendance? It was a change to a static_page and not any of the events CRUD page. 

Also, they think the calendar will be easier to look at and they don't care about mobile too much.

**Comment by haugerbr** [comment]
Because I'm pretty sure the view referenced that file unless we duplicated the code. Even if the CRUD model is still intact, if the view got broken it's pretty much useless. Even though I know you're doing this because the eboard wanted it, please tell me you understand how bad it is to change it to an iframe.

**Comment by rayfarias56** [comment]
Lol, yes, I know how bad this is... um, at least design wise, I don't know if you hinted at security issues. I can't think of any security problems, as it's coming from Google. What do you suggest to do here? I could easily fix any attendance tracking issues.

**Comment by haugerbr** [comment]
I would suggest that we find out what they wanted from the iframe and
implement that as a pure html\css solution so that it can still be
responsive and won't look out of place like an iframe.

On Sat, Nov 21, 2015 at 12:50 PM, Raymond Farias <notifications@github.com>
wrote:

> Lol, yes, I know how bad this is... um, at least design wise, I don't know
> if you hinted at security issues. I can't think of any security problems,
> as it's coming from Google. What do you suggest to do here? I could easily
> fix any attendance tracking issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rayfarias56/shpe/issues/124#issuecomment-158680027>.
>



-- 
Sincerely,
     Brian Hauger

**Comment by rayfarias56** [comment]
We'd have to make that look and feel like a calendar in order to make the eboard happy. Let's use an iframe for the time being, but make an html/css solution high priority for the next milestone. I'll also file an issue to test the attendance card reader in this milestone.

**Comment by haugerbr** [comment]
Sounds good.

On Tue, Nov 24, 2015 at 10:03 AM, Raymond Farias <notifications@github.com>
wrote:

> We'd have to make that look and feel like a calendar in order to make the
> eboard happy. Let's use an iframe for the time being, but make an html/css
> solution high priority for the next milestone. I'll also file an issue to
> test the attendance card reader in this milestone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rayfarias56/shpe/issues/124#issuecomment-159357746>.
>



-- 
Sincerely,
     Brian Hauger

**Comment by rayfarias56** [comment]
Actually, @haugerbr, how does this look? 

https://profromgo.com/blog/google-calendar-responsive/

Could be a solution.
