### ISSUE TITLE
Ability for Admins to add/remove sponsors

### ISSUE THREAD

**Issue by haugerbr** [rayfarias56/shpe#65]

**Comment by rayfarias56** [comment]
As @haugerbr mentioned in #99, look into using <a href="https://www.ruby-toolbox.com/projects/rmagick">Rmagick.</a>

**Comment by rayfarias56** [comment]
Also, updating sponsors should be a privilege given only to Admins, Presidents, and External Vps, but will only apply once #135 is resolved.
