### ISSUE TITLE
Sponsors Update

### ISSUE THREAD

**Issue by rayfarias56** [rayfarias56/shpe#99]
Investigate and update our corporate sponsors logo

**Comment by rayfarias56** [comment]
Palantir, P&G, Caterpillar, Microsoft, Abbvie, John Deere

@seanfreiburg and @haugerbr how did we get those watered out logos?

**Comment by haugerbr** [comment]
I believe @pzavala was the one that originally did that. I'll ask him or he can comment on this issue.

**Comment by haugerbr** [comment]
Found it
Steps to accomplishing this task:

Go to Pixlr.com and choose the Editor option
Open image that you want to grayscale
On toolbar Adjustment > Desaturate
Adjustment > Curves ...
Set the left point between 50% and 75% depending on how dark the image is
Save image and resize if necessary
Done!

**Comment by haugerbr** [comment]
We were going to write a tool to automatically add sponsors by providing a picture and a link so you could always do that to make this process less manual in the future.

**Comment by rayfarias56** [comment]
Thanks! If I have time I'll add in an admin/eboard feature to submit pictures and delete pictures. If not I think that's something easy for next semester. (Or more likely I'll just do that during winter break)

**Comment by haugerbr** [comment]
For the automated one you can look into using ImageMagick by using the ruby wrapper for it [Rmagick](https://www.ruby-toolbox.com/projects/rmagick).
